fsaclctl added

diff --git a/bin/mvim b/bin/mvim
--- a/bin/mvim
+++ b/bin/mvim
@@ -15,19 +15,19 @@
 
 if [ -z "$VIM_APP_DIR" ]
 then
-  myDir="`dirname "$0"`"
-  myAppDir="$myDir/../Applications"
-  for i in ~/Applications ~/Applications/vim $myDir $myDir/vim $myAppDir $myAppDir/vim /Applications /Applications/vim /Applications/Utilities /Applications/Utilities/vim; do
-    if [ -x "$i/MacVim.app" ]; then
-      VIM_APP_DIR="$i"
-      break
-    fi
-  done
+	myDir="`dirname "$0"`"
+	myAppDir="$myDir/../Applications"
+	for i in ~/Applications ~/Applications/vim $myDir $myDir/vim $myAppDir $myAppDir/vim /Applications /Applications/vim /Applications/Utilities /Applications/Utilities/vim; do
+		if [ -x "$i/MacVim.app" ]; then
+			VIM_APP_DIR="$i"
+			break
+		fi
+	done
 fi
 if [ -z "$VIM_APP_DIR" ]
 then
-  echo "Sorry, cannot find MacVim.app.  Try setting the VIM_APP_DIR environment variable to the directory containing MacVim.app."
-  exit 1
+	echo "Sorry, cannot find MacVim.app.  Try setting the VIM_APP_DIR environment variable to the directory containing MacVim.app."
+	exit 1
 fi
 binary="$VIM_APP_DIR/MacVim.app/Contents/MacOS/Vim"
 
@@ -39,19 +39,22 @@ gui=
 opts=
 
 # GUI mode, implies forking
-case "$name" in m*|g*|rg*) gui=true ;; esac
+case "$name" in m*|g*|rm*|rg*) gui=true ;; esac
 
 # Restricted mode
 case "$name" in r*) opts="$opts -Z";; esac
 
-# vimdiff and view
+# vimdiff, view, and ex mode
 case "$name" in
-  *vimdiff)
-    opts="$opts -dO"
-    ;;
-  *view)
-    opts="$opts -R"
-    ;;
+	*vimdiff)
+		opts="$opts -dO"
+		;;
+	*view)
+		opts="$opts -R"
+		;;
+	*ex)
+		opts="$opts -e"
+		;;
 esac
 
 # Last step:  fire up vim.
@@ -59,11 +62,11 @@ esac
 # not; we work around this when this script is invoked as "gvim" or "rgview"
 # etc., but not when it is invoked as "vim -g".
 if [ "$gui" ]; then
-  # Note: this isn't perfect, because any error output goes to the
-  # terminal instead of the console log.
-  # But if you use open instead, you will need to fully qualify the
-  # path names for any filenames you specify, which is hard.
-  exec "$binary" -g $opts ${1:+"$@"}
+	# Note: this isn't perfect, because any error output goes to the
+	# terminal instead of the console log.
+	# But if you use open instead, you will need to fully qualify the
+	# path names for any filenames you specify, which is hard.
+	exec "$binary" -g $opts ${1:+"$@"}
 else
-  exec "$binary" $opts ${1:+"$@"}
+	exec "$binary" $opts ${1:+"$@"}
 fi
